name: Daily Commit

on:
  schedule:
    - cron: "40 16 * * *"
  workflow_dispatch:

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make changes and commit
        run: |
          echo "$(date)" > last_run.txt
          git config --global user.name "GitHub Action"
          git config --global user.email "24f2005217@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated commit - $(date)"
          
      - name: Push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          git push origin main
